
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 02 04:13:59 CEST 2014
//----------------------------------------------------

package edu.pjwstk.demo.parser;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int AND = 13;
  public static final int MULTIPLY = 9;
  public static final int PLUS = 7;
  public static final int LESS_EQUAL = 18;
  public static final int OR = 14;
  public static final int BOOLEAN_LITERAL = 4;
  public static final int IDENTIFIER = 6;
  public static final int GREATER_EQUAL = 16;
  public static final int GREATER = 15;
  public static final int MODULO = 11;
  public static final int STRING_LITERAL = 5;
  public static final int EQUALS = 20;
  public static final int EOF = 0;
  public static final int DIVIDE = 10;
  public static final int MINUS = 8;
  public static final int NOT_EQUALS = 19;
  public static final int error = 1;
  public static final int RIGHT_ROUND_BRACKET = 22;
  public static final int INTEGER_LITERAL = 2;
  public static final int LEFT_ROUND_BRACKET = 21;
  public static final int XOR = 12;
  public static final int LESS = 17;
  public static final int DOUBLE_LITERAL = 3;
}

